backbone_arch: resnet18
# options: resnet18, resnet34, resnet50
pretrain_dir: 'runs/pixcl_20240415-084718' 
#pretrain_dir: None 
# Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
pretrain_epoch: '17'
#pretrain_epoch: None 
# specify epoch from a pre-trained model
downstream_arch: 'fcn8s'
# options are 'fcns', 'fcn8s', 'fcn16s', or 'fcn32s'

image:
  sizeH: 82
  sizeW: 100
  n_class: 1

trainer:
  val_percent: 0.1
  batch_size: 5 
  max_epochs: 100 
  num_workers: None 
  # for plasma max(num_workers) = 48, None - obtain from os.cpu_count() 

dataset:
  images_dir: 'REAL/imgs'
  mask_dir: 'REAL/masks'
  mask_suffix: '_mask'
  scale: 1.
  channels: 3 
  mask_values: [0, 255]

optimizer:
  lr: 0.0003
  weight_decay: 0.0004
